spring:
  main:
    web-application-type: reactive
  profiles:
    active: local # 프로덕션 기본값
  application:
    name: gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      client-name: ${REDIS_USER:default}
      password: ${REDIS_PASSWORD:1234}

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}