spring:
  cloud:
    gateway:
      routes:
        - id: module-game
          uri: localhost:8081

        - id: module-ticket
          uri: localhost:8082

        - id: module-auth
          uri: localhost:8083
          predicates:
            - Path=/api/v1/auth/**, /api/v1/members