spring:
  cloud:
    gateway:
      routes:
        - id: module-game
          uri: http://localhost:8081
          predicates:
            - Path=/api/v*/games/**, /api/v*/seats/**, /api/v*/sections/**, /api/v*/stadiums/**
          filters:
#            - name: ValidateToken
            - RewritePath=/module-game/(?<segment>.*), /${segment}

        - id: module-ticket
          uri: http://localhost:8082
          predicates:
            - Path=/api/v*/tickets/**, /api/v*/reservations/**, /api/v*/waiting-queue/**
          filters:
#            - name: ValidateToken
            - RewritePath=/module-ticket/(?<segment>.*), /${segment}

        - id: module-auth
          uri: http://localhost:8083
          predicates:
            - Path=/api/v*/auth/**

        - id: member
          uri: http://localhost:8083
          predicates:
            - Path=/api/v*/members/**
          filters:
            - name: ValidateToken
            - RewritePath=/member/(?<segment>.*), /${segment}

#        - id: module-auction
#          uri: http://localhost:8084

#        - id: module-waiting
#          uri: http://localhost:8085

        - id: module-point
          uri: http://localhost:8086
          predicates:
            - Path=/api/v*/members/**
          filters:
            - name: ValidateToken
            - RewritePath=/point-module/(?<segment>.*), /${segment}

        - id: admin-game
          uri: http://localhost:8081
          predicates:
            - Path=/api/v*/admin/**
          filters:
#            - name: ValidateToken
#              args:
#                requiredRole: ROLE_ADMIN
            - RewritePath=/admin-game/(?<segment>.*), /${segment}
      httpclient:
        pool:
          maxConnections: 1000
          acquireTimeout: 10000
        connect-timeout: 10000
        response-timeout: 60000


        - id: exchange-point
          uri: http://localhost:8086
          predicates:
            - Path=/api/v*/admin/**
          filters:
            - name: ValidateToken
              args:
                requiredRole: ROLE_ADMIN
            - RewritePath=/exchange-point/(?<segment>.*), /${segment}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, gateway