spring:
  cloud:
    gateway:
      routes:
        - id: module-game
          uri: lb://module-game
          predicates:
            - Path=/api/v*/games/**, /api/v*/seats/**, /api/v*/sections/**, /api/v*/stadiums/**
          filters:
            - name: ValidateToken
            - RewritePath=/module-game/(?<segment>.*), /${segment}


        - id: module-ticket
          uri: lb://module-ticket
          predicates:
            - Path=/api/v*/tickets/**, /api/v*/reservations/**, /api/v*/waiting-queue/**
          filters:
            - name: ValidateToken
            - RewritePath=/module-ticket/(?<segment>.*), /${segment}


        - id: auth-login
          uri: lb://module-login
          predicates:
            - Path=/api/v*/auth/login
          filters:
            - name: RequestRateLimiter
              args:
                keyResolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1   # 초당 최대 1 토큰 생성
                redis-rate-limiter.burstCapacity: 2   # 2 토큰시 버스트


        - id: auth-signup
          uri: lb://module-auth
          predicates:
            - Path=/api/v*/auth/signup


        - id: auth-member
          uri: lb://module-member
          predicates:
            - Path=/api/v*/members/**
          filters:
            - name: ValidateToken
            - RewritePath=/auth-member/(?<segment>.*), /${segment}


        - id: module-auction
          uri: lb://module-auction
          predicates:
            - Path=/api/v*/auctions/**
          filters:
            - name: ValidateToken
            - RewritePath=/module-auction/(?<segment>.*), /${segment}


        - id: module-point
          uri: lb://module-point
          predicates:
            - Path=/api/v*/points/**, /api/v*/pointHistories/**, /api/v*/payments/**
          filters:
            - name: ValidateToken
            - RewritePath=/module-point/(?<segment>.*), /${segment}


        - id: admin-game
          uri: lb://module-game
          predicates:
            - Path=/api/v*/admin/games/**, /api/v*/admin/sections/**, /api/v*/admin/seats/**, api/v*/admin/stadiums/**
          filters:
            - name: ValidateToken
              args:
                requiredRole: ROLE_ADMIN
            - RewritePath=/admin-game/(?<segment>.*), /${segment}


        - id: exchange-point
          uri: lb://module-point
          predicates:
            - Path=/api/v*/admin/points/**, /api/v*/admin/exchangeHistories/**
          filters:
            - name: ValidateToken
              args:
                requiredRole: ROLE_ADMIN
            - RewritePath=/exchange-point/(?<segment>.*), /${segment}

      httpclient:
        pool:
          maxConnections: 1000
          acquireTimeout: 10000
          connect-timeout: 10000
          response-timeout: 60000


management:
  endpoints:
    web:
      exposure:
        include: prometheus, gateway