spring:
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: module-game
          uri: http://localhost:8081
          predicates:
            - Path=/api/v*/games/**, /api/v*/seats/**, /api/v*/sections/**, /api/v*/stadiums/**
          filters:
            - name: ValidateToken
            - RewritePath=/module-game/(?<segment>.*), /${segment}


        - id: module-ticket
          uri: http://localhost:8082
          predicates:
            - Path=/api/v*/tickets/**, /api/v*/reservations/**, /api/v*/waiting-queue/**
          filters:
            - name: ValidateToken
            - RewritePath=/module-ticket/(?<segment>.*), /${segment}


        - id: auth-login
          uri: http://localhost:8083
          predicates:
            - Path=/api/v*/auth/login
          filters:
            - name: RequestRateLimiter
              args:
                keyResolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1   # 초당 최대 1 토큰 생성
                redis-rate-limiter.burstCapacity: 2   # 2 토큰시 버스트


        - id: auth-signup
          uri: http://localhost:8083
          predicates:
            - Path=/api/v*/auth/signup


        - id: auth-member
          uri: http://localhost:8083
          predicates:
            - Path=/api/v*/members/**
          filters:
            - name: ValidateToken
            - RewritePath=/auth-member/(?<segment>.*), /${segment}


        - id: module-auction
          uri: http://localhost:8084
          predicates:
            - Path=/api/v*/auctions/**
          filters:
            - name: ValidateToken
            - RewritePath=/module-auction/(?<segment>.*), /${segment}


#        - id: module-waiting
#          uri: http://localhost:8085


        - id: module-point
          uri: http://localhost:8086
          predicates:
            - Path=/api/v*/members/**
          filters:
            - name: ValidateToken
            - RewritePath=/point-module/(?<segment>.*), /${segment}


        - id: admin-game
          uri: http://localhost:8081
          predicates:
            - Path=/api/v*/admin/**
          filters:
            - name: ValidateToken
              args:
                requiredRole: ROLE_ADMIN
            - RewritePath=/admin-game/(?<segment>.*), /${segment}


        - id: exchange-point
          uri: http://localhost:8086
          predicates:
            - Path=/api/v*/admin/**
          filters:
            - name: ValidateToken
              args:
                requiredRole: ROLE_ADMIN
            - RewritePath=/exchange-point/(?<segment>.*), /${segment}


management:
  endpoints:
    web:
      exposure:
        include: prometheus, gateway