name: CI

on:
  pull_request:
    branches: ["develop"]
    types: [opened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed file
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            module-*/**
            build.gradle
            settings.gradle

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Gradle dependencies caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test changed modules
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          MODULES=("auth", "game", "ticket", "module")
          
          # 공통 코드 변경 시 모든 모듈 빌드
          build_all_modules() {
            echo "Common files changed, building all modules..."
            ./gradlew build
          }

          # 특정 모듈만 빌드
          build_module() {
            local module=$1
            echo "Building and testing module-$module..."
            ./gradlew :module-$module:build
          }

          # 공통 코드 변경 확인
          if echo "$CHANGED_FILES" | grep -q "module-common/\|build.gradle\|settings.gradle"; then
            build_all_modules
          else
            for MODULE in "${MODULES[@]}"; do
              if echo "$CHANGED_FILES" | grep -q "module-$MODULE/"; then
                build_module "$MODULE"
              fi
            done
          fi